### ISSUE TITLE
Should add convention on number format

### ISSUE THREAD

**Issue by nicohusser** [GroupePSA/api-standards#1]
JSON itself defines a number very simply: it is an unbounded, fixed-point value. This is illustrated well by the railroad diagram for number at JSON. There is only one number type in JSON; there is no separate integer type.

JSON Schema diverges from JSON and defines two number types: number and integer. This is purely a convenience for schema validation; the JSON number type is used to implement both. Just as in JSON, both types are unbounded unless the schema author provides explicit minimum and maximum values.

How do we do ? Are there any constraint at PSA ?

**Comment by axel3rd** [comment]
@adrienlauer / @nicnhus22 : Closed issue ? Fixed by #4 ...
