### ISSUE TITLE
Misleading information on security issues with query parameters

### ISSUE THREAD

**Issue by ronau** [GroupePSA/api-standards#12]
I think the mentioned security issue regarding the use of query parameters is slightly misleading:
https://github.com/GroupePSA/api-standards/blob/master/api-style-guide.md#query-parameters

> Be careful when using sensitive/private query parameters as the URI is not encrypted over HTTPS

This is not quite correct. Using TLS, usually only the hostname and the port are unencrypted, thus visible easily. The (context) path as well as the query parameters are TLS encrypted indeed.

It could be mentioned, however, that full URLs and query parameters are usually included in logfiles, so the recommendation to be careful with sensitive/private parameters is still valid.

**Comment by axel3rd** [comment]
@ronau : Many thanks for you feedback. This item needs an improvement.
@adrienlauer : Have you an idea to be more precise about that ?

**Comment by adrienlauer** [comment]
@ronau: The proposed change is in the PR #13. Let me know what you think if you can but I think it fixes the issue.

**Comment by axel3rd** [comment]
We can go ahead with that 👍 , exchange can continue.

**Comment by ronau** [comment]
I agree. Looks good now. 👍
