### ISSUE TITLE
Should add convention on asynchronism

### ISSUE THREAD

**Issue by nicohusser** [GroupePSA/api-standards#2]
Do we enforce webhooks or polling? Any constratins at PSA regarding webooks ?

**Comment by NoeReboul** [comment]
There's also websockets for this purpose. What's your opinion ?

**Comment by nicohusser** [comment]
We kept that in mind, we'll discuss this today with the team. For now my opinion is that websockets do not belong to the scope of this document : "Standards and guidelines for Groupe PSA **REST APIs.**". However I do think that we need to standardize their usage too.

**Comment by nicohusser** [comment]
@NoeReboul : as discussed with @adrienlauer, websockets is a complex and vast subject - it must be treated separately. We'll keep that in mind though :)
