### ISSUE TITLE
Separate high-level topics in distinct parts

### ISSUE THREAD

**Issue by adrienlauer** [GroupePSA/api-standards#4]
For the sake of simplicity, I think the guide should be split in at least three parts: 

* The current style guide with some parts removed (see other points),
* A part about the data formats: numbers (see #1), dates, geolocation (see #3), ...
* A part about security. 

The current style guide holds too much information in one place.

**Comment by nicohusser** [comment]
I agree. Will do when the content has been validated : the current format (one pager) is easier to maintain.

**Comment by nicohusser** [comment]
Closing, as discussed over the phone.
