### ISSUE TITLE
HTTP Response code 304

### ISSUE THREAD

**Issue by tyazid** [GroupePSA/api-standards#6]
Based on [Cache](https://github.com/GroupePSA/api-standards/blob/master/api-style-guide.md#caching) section, we expect to have code 304 as a supported response code also in [HTTP Method to Status Code Mapping](https://github.com/GroupePSA/api-standards/blob/master/api-style-guide.md#http-method-to-status-code-mapping) section (but unfortunately not supported since not mentioned among the allowed code "API developers SHOULD use only").

**Comment by nicohusser** [comment]
The mapping should be read as follows : "For each HTTP method, API developers SHOULD use only status codes marked as "X" in this table", as stated above the table. However, that does not mean that developers cannot use status codes that aren't in the table. In fact, developers can use status codes as listed in section "Status Codes List". The mapping method/status code is simply for common HTTP methods.
